### ISSUE TITLE
Dangerous Beds in Default Lobby

### ISSUE THREAD

**Issue by lyubitto** [MarkusBordihn/BOs-Lobby#1]
**PROBLEM**
Beds appear in the default lobby dimension, however... 
`"bed_works": false,` 
https://github.com/MarkusBordihn/BOs-Lobby/blob/55a9da663e90ee10408a7c09a975822a6d7a506c/src/main/resources/data/lobby/dimension_type/lobby_dimension.json#L4
as a default setting is brutal when considering the default lobby. Beds have been placed, but each one is a bomb ready to burn down the buildings containing them.

**SOLUTION**
Simply flip this line to be TRUE by default, so nobody walks upstairs and right clicks a bed out of curiosity. 

**ALTERNATIVE** **SOLUTIONS**
If the explosive beds are indeed an intentional default for the Lobby dimension, giving an admin more immediate access to that variable would be extremely helpful. A toggle in Mod Settings might be the most obvious, or more likely a command such as `/lobbyconfig bed_works [true/false]`
Other off-hand ideas
- build houses out of a material that will not catch fire after a player causes a bed to explode
- offer a command that resets the lobby to default state (maybe later allow player to define what Default State looks like)
- provide a "safe space" with a bed on it for a player to right-click as soon as they join the lobby. And a button to reset the Education Space for any future players. This is the least fleshed-out idea and I have no idea how to even begin to implement it.

**Additional context**
I understand that the best case scenario is that whoever creates the world will customize the lobby and notice that beds are Explosive. However I also have a feeling that a large percentage of users will simply download this mod and apply the most barebones of basics to make the mod seem functional.

**Comment by MarkusBordihn** [comment]
Thanks a lot for the detailed report. I changed the settings, uploaded a new version and will working on a flag to make the lobby fire-proofed.

Because I already destroyed some building with fire, I recently created an [fire extinguisher](https://www.curseforge.com/minecraft/mc-mods/fire-extinguisher).

But anyways thanks a lot for the report and will add some additional safety switches in the next version.
