### ISSUE TITLE
Interacting with Armorer in Mining Dimension crashes server

### ISSUE THREAD

**Issue by mimi-min** [MarkusBordihn/BOs-Lobby#11]
**Describe the bug**
When we interact with the Armorer in the mining dimension, the server crashes

**To Reproduce**
1. Go to Mining Dimension
2. Right-click on Armorer

**Expected behavior**
A shop menu to open up

**Screenshots**

**Debugging**
Console log: https://pastebin.com/RJq8jj1c
Crash log; https://pastebin.com/YZH0QEhB

**Is the issue happening in combination with other mods? (If yes, please provide a full list)**
List is in crash log.

**Additional context**
~~I haven't checked other NPCs yet, but it's happened twice.~~

Can confirm, it happens with NPCs in other dimensions as well.

**Comment by MarkusBordihn** [comment]
Thanks for the report. I assume that the **Armorer** is consider as kind of **loot chest** which are automatically cleared inside the mining dimension.

You could solve this issue by setting the "miningRemoveLootChest" option to `false` inside the `lobby-common.toml` config file and restart the server.

If you send me the related mod link, I will try implement a patch to skip these entities for this option.

> Can confirm, it happens with NPCs in other dimensions as well.

If this happens with other NPCs in other dimension as well, it seems not related to this mod.
The mod is only adjusting the spawn and entities in the mining dimension, but not for the other dimension like the over-world or so.

**Comment by MarkusBordihn** [comment]
I just run some additional tests with my mod pack and it seems that the issue is not related to this mod at all.
I was able to trade and level the NPC fine, regardless of the **miningRemoveLootChest** option, so I assume that this is an issue with some of the mods which modify the trading of the villager NPCs.

![image](https://user-images.githubusercontent.com/12183293/184429785-52e462d7-97aa-4c24-838a-d1b7241512b3.png)

**Comment by mimi-min** [comment]
Thanks for looking into it for me! I think it's an issue with  mod called "Our Villager Discounts" instead, so I'll look into that.

Thanks again!
