### ISSUE TITLE
How can you disable this mod without turning it off?

### ISSUE THREAD

**Issue by Health1nspector** [MarkusBordihn/BOs-Lobby#13]
I hate how it teleports me to the fishing spot automatically, but when I turn off the mod it tells me to put my MC is safe mode. Please tell me how I can disable the automatic teleporting.

**Comment by MarkusBordihn** [comment]
You need to edit the `lobby-common.toml` file inside your config directory like:
![image](https://user-images.githubusercontent.com/12183293/198826989-8542aea4-388d-449c-bccc-72ff328878be.png)

Inside the config you can adjust the values, if all generalDefault... are set to "false" there should be no automatic teleportation.
![image](https://user-images.githubusercontent.com/12183293/198827051-e15cbcfe-d796-4206-a815-2c10692d877c.png)

Please keep in mind that you should only edit the file when the game/server is not running.

If you want to remove the mod and the dimensions, please take a look at https://github.com/MarkusBordihn/BOs-Lobby/blob/main/doc/HOW_TO_RESTORE_YOUR_WORLD.md instead.
