### ISSUE TITLE
Server config not working

### ISSUE THREAD

**Issue by Sebaspc97** [MarkusBordihn/BOs-Lobby#14]
**Describe the bug**
I have the server config like the image and after every server restart, it forces lobby teleport anyway.

lobby 1.20.1 - 8.0.0
forge 47.1.0

**To Reproduce**

**Expected behavior**

**Screenshots**
![1](https://github.com/MarkusBordihn/BOs-Lobby/assets/96534073/730a7bf8-9432-4d23-9bb0-9a98034e9873)

**Debugging**
Before reporting a issue please check if there is anything relevant in the crash-reports, debug.log and latest.log file.

**Is the issue happening in combination with other mods? (If yes, please provide a full list)**

**Additional context**

**Comment by MarkusBordihn** [comment]
Thanks for the report. Unfortunately I'm unable to reproduce the issue my self.
Could you please provide the following additional details.

### debug.log / latest.log 
This file contains detail like:
```
[12:30:05] [Server thread/INFO] [Lobby/]: [Lobby Teleport Manager] Only teleports the player once to the lobby with their first connect!
[12:30:05] [Server thread/INFO] [Lobby/]: [Lobby Teleport Manager] Using stored Player Teleport List to limiting automatic transfers to lobby: [380df991-f603-344c-a090-369bad2a924a]
```

### dimensions/lobby/lobby_dimension/data/lobby.dat file
This file contains the list of already teleported players like.
![image](https://github.com/MarkusBordihn/BOs-Lobby/assets/12183293/2aa3a158-63c8-4c71-8fa4-bf42729d19fb)

The list is using the UUID of the player if the UUID is changing this feature will not work. Thanks.
