### ISSUE TITLE
Chests Don't Spawn as Lootr Chests

### ISSUE THREAD

**Issue by Kangy1103** [MarkusBordihn/BOs-Lobby#17]
**Describe the bug**
Not sure if this is the fault of this mod but reporting it in both places to be on the safe side. None of the chests that spawn in the dimension spawn as Lootr chests. They spawn as normal chests.

**To Reproduce**
1. Go to Mining Dimension
2. Find Chest
3. See it's a normal chest

**Expected behavior**
Chests should spawn as Lootr chests

Maybe I missed a config option but it would be nice to get them to play ball :)

**Comment by MarkusBordihn** [comment]
I tried to reproduce the issue with my reference modpack https://www.curseforge.com/minecraft/modpacks/bos-adventure-world but was not able to reproduce the issue. All of the spawned expected chests are Lootr chests.

Please keep in mind that there are config options like `miningRemoveLootChest`, `miningDisableMinecartChestSpawning` and `miningRemoveSpawner` for the Mining Dimension, which could be the reason in your case.

If you checked the config and restarted the game/server and still have this kind of issue, please provide more details like the exact versions numbers and kind of mods which are installed. Thanks.

**Comment by Kangy1103** [comment]
> I tried to reproduce the issue with my reference modpack https://www.curseforge.com/minecraft/modpacks/bos-adventure-world but was not able to reproduce the issue. All of the spawned expected chests are Lootr chests.
> 
> Please keep in mind that there are config options like `miningRemoveLootChest`, `miningDisableMinecartChestSpawning` and `miningRemoveSpawner` for the Mining Dimension, which could be the reason in your case.
> 
> If you checked the config and restarted the game/server and still have this kind of issue, please provide more details like the exact versions numbers and kind of mods which are installed. Thanks.

I think you may be right with those config options. I just checked them and they were all set to true though I was sure I had set them to false previously. Changing them now, will regenerate the dimension and test further. Thank you!
