### ISSUE TITLE
How do I change the Countdown text?

### ISSUE THREAD

**Issue by Deafpie** [MarkusBordihn/BOs-Lobby#19]
**Describe the bug**
A clear and concise description of what the bug is:
When the game is counting down after doing /lobby,
it says stuff like:
text.lobby.teleport_remaining
text.lobby.teleport_remaining
text.lobby.teleport_remaining

**To Reproduce**

**Expected behavior**

**Screenshots**

**Debugging**
Before reporting a issue please check if there is anything relevant in the crash-reports, debug.log and latest.log file.

**Is the issue happening in combination with other mods? (If yes, please provide a full list)**

**Additional context**

**Comment by MarkusBordihn** [comment]
This happens when the mod is only installed on the server and not on the client.

The mod is supporting translated text, which mean it needs to be installed on the client as well to display the translated text instead of these placeholders.
