### ISSUE TITLE
Weird Text when using commands

### ISSUE THREAD

**Issue by Deafpie** [MarkusBordihn/BOs-Lobby#20]
**Describe the bug**
When doing /lobby, it says things like:
text.lobby.teleport_remaining
text.lobby.teleport_remaining
text.lobby.teleport_remaining
text.lobby.teleport_remaining
text.lobby.failed_cooldown
text.lobby.teleport_abort

here is an example: https://prnt.sc/UczD9Y5jipHb

How do I change these?
thanks!

**Comment by MarkusBordihn** [comment]
Duplicate of #19
