### ISSUE TITLE
Flooded mining camp

### ISSUE THREAD

**Issue by littlepianist** [MarkusBordihn/BOs-Lobby#3]
![2022-01-31_03 36 51](https://user-images.githubusercontent.com/75674050/151749804-ae66d7f1-7e70-468b-b223-9f3dd524a6b3.png)

**Comment by MarkusBordihn** [comment]
Thanks for the report, I tried to auto-generated about 800 worlds and none of them have a flooded cave. :(
Could it be that you installed a mod which changed the default world generation?

But anyways I solved the issue by adding a tent to the mining base as spawn which has some hidden sponges to make sure you are not drowning.

<img width="1240" alt="image" src="https://user-images.githubusercontent.com/12183293/151878551-e94d1793-131f-4311-9216-48521b49584b.png">

The new mining base will be part of the next release in the next few days.
To reset your mining dimension, just delete the mining dimension folder **dimensions/mining_dimension**.
