### ISSUE TITLE
Mod does not work on Servers

### ISSUE THREAD

**Issue by IchigoGames** [MarkusBordihn/BOs-Lobby#4]
**Describe the bug**
On server when you type /lobby or /mining it says the dim name is not loaded so for example /mining cannot teleport mining Dimension is not loaded extra issue is not good to take over /spawn command what if some one in overworld wants to get to spawn this mod makes it so they cant.

**To Reproduce**
1. Go to A server with modinstalled
2.type command
3. see that nothing happens no teleport

**Expected behavior**
for it to work the same as singleplayer

**logs**
[latest.log](https://github.com/MarkusBordihn/BOs-Lobby/files/8009289/latest.log)

**Screenshots**
![image](https://user-images.githubusercontent.com/11888162/152665602-e7a8b8cb-739d-4901-946f-570f88c5488b.png)
![image](https://user-images.githubusercontent.com/11888162/152665606-ed38f6b7-aedc-4863-922e-d0f3a2427fe4.png)
![image](https://user-images.githubusercontent.com/11888162/152665616-e14a5398-ab1e-4f00-a576-89b0c383b457.png)

**Is the issue happening in combination with other mods? (If yes, please provide a full list)**                                                      Modpack is The New Frontier Enhanced 2.2

**Comment by MarkusBordihn** [comment]
Thanks for the report. I'm not really able to reproduce the issue with the mod alone or on any of my servers.
It's seems that's an issue with one of the mods of the mod pack or the server itself instead.

I will try to reproduce the issue with the mod pack and will see what I could do to fix the issue.

Could you let me know what's happen when you run the following commands on your server with the mod:

- /forge dimensions
- /datapack list

The output should be something like:
```
[14:02:26 INFO]: Currently registered dimensions by type:
[14:02:26 INFO]: lobby:fishing_dimension: lobby:fishing_dimension
[14:02:26 INFO]: lobby:lobby_dimension: lobby:lobby_dimension
[14:02:26 INFO]: lobby:mining_dimension: lobby:mining_dimension
[14:02:26 INFO]: minecraft:overworld: minecraft:overworld
[14:02:26 INFO]: minecraft:the_end: minecraft:the_end
[14:02:26 INFO]: minecraft:the_nether: minecraft:the_nether
```

and

```
[14:04:48 INFO]: There are 9 data packs enabled: [vanilla (built-in)], [mod:lobby], [mod:spark], [mod:itemzoom], [mod:jade], [mod:forge], [mod:jei], [mod:worldedit], [mod:xaerominimap]
[14:04:48 INFO]: There are no more data packs available
```

The dimensions are generated over standard data packs, so if this fails there is something wrong on the server.

By the way the mod "EasierSleeping-1.18.1-2.1.0.jar" is not really need in your data-pack for 1.18.1, because there is a game-rule for this.

**Comment by MarkusBordihn** [comment]
Ok, I tested the following files:
- https://www.curseforge.com/minecraft/mc-mods/lobby/files/3630465
- https://www.curseforge.com/minecraft/modpacks/the-new-frontier-enhanced/files/3638264

Run's fine and created the corresponding dimensions, see:
<img width="952" alt="image" src="https://user-images.githubusercontent.com/12183293/152682967-7505a29b-b32a-494c-bffd-33a39f135c62.png">

I'm not able to reproduce the issue with your provided mod-pack and the latest version of the lobby mod.
This means it's any issue with the server itself and not an general issue with the mod.

But let me know what's the output of the following two commands on your server, maybe we could isolate the issue:
- /forge dimensions
- /datapack list

**Comment by IchigoGames** [comment]
ok ill do that tonight and let you know

**Comment by IchigoGames** [comment]
![image](https://user-images.githubusercontent.com/11888162/152721570-0472eb91-3ad1-4d9c-9d7a-8e25c2df2cc1.png)
![image](https://user-images.githubusercontent.com/11888162/152721610-788c5d6e-1c8e-4a5e-8bcb-fc9ce4353ac6.png)

**Comment by IchigoGames** [comment]
![image](https://user-images.githubusercontent.com/11888162/152721661-5583775f-4852-4077-912c-b4c595cc326c.png)
ran the commands it does not look like the mods dimensions are Registered and say msg when you try to use commands

**Comment by IchigoGames** [comment]
[latest.log](https://github.com/MarkusBordihn/BOs-Lobby/files/8012186/latest.log) updated log
its probably a mod conflict or something ill do more testing next week when i work on modpack.

**Comment by MarkusBordihn** [comment]
Thanks for the update. According the log file you have a bigger problem on the server / with the world.

I can see that none of the custom dimension, even from other mods besides the "ae2:spatial_storage" are created.
For example bonsaitrees3 is using the bonsaitrees3:growtown dimension which is also missing according your log.

There are two possible reason for this:

- Your world data / data pack is corrupt and the dimension generation is blocked for safety reasons.
- A mod is overwriting the dimension / biome generation and blocks the creation of other dimensions.

I'm assume that you will not be able to reproduce the issue on a new world on the same server.

I found a similar reported issue like this: https://www.reddit.com/r/feedthebeast/comments/rzmlxx/forge_1181_custom_modpack_mods_that_add/

At the moment there is unfortunately nothing which I could do from my side to solve this dedicated issue.

You can try to backup your world and open it (with your modpack) and a client to run the Minecraft "Optimize world" option to see if this is able to fix some of the world related issues.

**Comment by IchigoGames** [comment]
oh ok thank you for looking into it i knew i might have to reset world soon sense iv also seen corrupted world gen in the overworld ill work on it this weekend and give the mod another try.

**Comment by yatsukiko** [comment]
For anyone stumbling on this, I got it "fixed" by loading the world in singleplayer, after that dimensions should generate normally and i'm able to warp to them, after that i put it on server and it worked just fine. If that doesnt work for you, you can try removing terraforged(afaik it doesn't work on servers yet, or at least not in my case) or other biome related mods (biomes o plenty worked just fine).
