### ISSUE TITLE
Extra config options

### ISSUE THREAD

**Issue by YOYOK9** [MarkusBordihn/BOs-Lobby#6]
**Is your feature request related to a problem? Please describe.**
2 issues, but still config related: 
First:
My server restarts twice a day and sometimes players are in other dimensions exploring when this happens, and unfortunately it seems there is a 50/50 chance of actually being sent to the lobby on reconnect. (this sometimes happens on relogs as well) Meaning their options are either go to spawn or tp home, either way they loose their last location. 

Will note: generalDefaultToLobbyAlways is also set to false. 

Second:
Would like to eventually add something like a player market to the lobby dim for players to buy/sell items. Possible to do this in adventure modes sort of but would be easier if I could set them to survival while they build their shops. 

**Describe the solution you'd like**
First: 
Basically wondering if it would be possible to add either an extra option or sub option for the "generalDefaultToLobby" option to allow only first time spawns to go there. 
something like: firsttimeLobbyOnly (I suck at names) is enabled and the other option is on or off it will only send new players. 

Second: 
a config option for builders in survival (like the creative option) 
ex: LobbySurvivalBuilders = [""] 

**Describe alternatives you've considered**
First:
I know I could in theory just disable this option, However that would also stop New users from spawning there. 

Second:
Can also just manually set the survival gamemode for those players each time they enter the dim. Or have the ability (without datapacks) to set the gm in the config and use another mod for protection. 

**Additional context**

Can explain in a bit more detail if needed or split the 2 features into 2 separate requests if needed as well

**Comment by MarkusBordihn** [comment]
Thanks for the suggestions, I will try to add them in the next release version.

**Comment by YOYOK9** [comment]
I have updated to the new version that adds this, but have run into an issue, Users still get sent to the lobby after a server restart, even though I only have the "generalDefaultToLobbyOnce" set to True. 


My config settings on server + Client: 
        generalCommandCoolDown = 30
	#Teleports the player to the lobby for their first connect or after a server restart!
	generalDefaultToLobby = false
	#Only teleports the player once to the lobby with their first connect!
	generalDefaultToLobbyOnce = true
	#Always teleport player to the lobby!
	generalDefaultToLobbyAlways = false

**Comment by MarkusBordihn** [comment]
Thanks for the report. I was able to reproduce the issue and released a fix as:
https://www.curseforge.com/minecraft/mc-mods/lobby/files/3810856

I currently testing the fix on my server and it looks fine so far, but let me know if the fix still shows any issue on your side.

**Comment by YOYOK9** [comment]
The new update seems to have fixed the issue. Thanks.
