### ISSUE TITLE
[Feature Request]: Dimension name translation feature request + Attach a Korean translation file 

### ISSUE THREAD

**Issue by ssolephant** [MarkusBordihn/BOs-Lobby#8]
**Is your feature request related to a problem? Please describe.**

 I translated the file, but there were words I couldn't change.
Please refer to the attached photo below.
![image](https://user-images.githubusercontent.com/94880625/175719495-07c67f09-f3bd-4060-8215-1ef19dcd9049.png)

**Describe the solution you'd like**

 I wish there was a function to replace or translate words.

**Describe alternatives you've considered**

 Create a phrase to change Default, Fishing, Gaming, Lobby, Mining, Void in the json file located in "assets\lobby\lang".
Alternatively, make it possible to change the Default, Fishing, Gaming, Lobby, Mining, Void wording in the "lobby-common.toml" file.

**Additional context**

 I can't upload the translated Json file, so I'll upload the text and txt file.

[ko_kr.txt](https://github.com/MarkusBordihn/BOs-Lobby/files/8982469/ko_kr.txt)

{
  "text.lobby.welcome_to_default": "일반 차원에 오신 것을 환영합니다, %1$s, %3$s 또는 %4$s 명령어를 입력해서 다른 차원으로 이동할 수 있습니다",
  "text.lobby.welcome_to_fishing": "낚시 차원에 오신 것을 환영합니다, %3$s, %4$s 또는 %5$s 명령어를 입력해서 다른 차원으로 이동할 수 있습니다",
  "text.lobby.welcome_to_gaming": "게이밍 차원에 오신 것을 환영합니다, %1$s, %3$s 또는 %5$s 명령어를 입력해서 다른 차원으로 이동할 수 있습니다",
  "text.lobby.welcome_to_lobby": "로비에 오신 것을 환영합니다, %1$s, %4$s 또는 %5$s 명령어를 입력해서 다른 차원으로 이동할 수 있습니다",
  "text.lobby.welcome_to_mining": "광산 차원에 오신 것을 환영합니다, %1$s, %3$s 또는 %5$s 명령어를 입력해서 다른 차원으로 이동할 수 있습니다",
  "text.lobby.welcome_to_void": "공허 차원에 오신 것을 환영합니다, %1$s, %3$s 또는 %5$s 명령어를 입력해서 다른 차원으로 이동할 수 있습니다",

  "text.lobby.failed_already_in_dimension": "이미 %1$s 차원에 있어서 차원 이동에 실패했습니다",
  "text.lobby.failed_cooldown": "쿨타임이여서 %1$s 차원 이동에 실패했습니다, %2$s초 후에 차원 이동 명령어를 다시 사용할 수 있습니다",
  "text.lobby.teleport_to": "%1$s차원으로 이동 중입니다, 가만히 기다려주세요!",
  "text.lobby.teleport_to_in": "%2$s초 후에 %1$s 차원으로 이동합니다,  가만히 기다려주세요!",
  "text.lobby.teleport_abort": "움직여서 %1$s 차원으로 이동이 중단되었습니다!",
  "text.lobby.teleport_remaining": "%2$s초 내에 %1$s 차원으로 이동합니다...",
  "text.lobby.transfer_to_lobby": "잠시 기다리시면, 로비로 이동됩니다! 만약 이동되지 않았다면 %1$s 명령어로 차원 이동 할 수 있습니다",
  "text.lobby.unable_to_teleport": "%2$s 차원을 불러올 수 없어서 %1$s 차원으로 이동할 수 없습니다!",

  "biome.lobby.biome_fishing": "낚시 차원",
  "biome.lobby.biome_gaming": "게이밍 차원",
  "biome.lobby.biome_lobby": "로비",
  "biome.lobby.biome_void": "공허 차원"
}

**Comment by MarkusBordihn** [comment]
Thanks a lot for the report this should be fixed now.
You can change the dimension names directly in the config file.
